### ISSUE TITLE
Chrome autofill overrides font

### ISSUE THREAD

**Issue by glenndevenish** [bstashio/bulma-customizer#4]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.4
My **browser** is: Chrome 74.0.3729.157 (Official Build) (64-bit) (cohort: Stable)

### Description

Chrome autofill edits font styling. Here is the relevant section from the default stylesheet:
```css
input:-internal-autofill-previewed {
    font-family: system-ui !important;
    background-color: rgb(232, 240, 254) !important;
    background-image: none !important;
    color: rgb(0, 0, 0) !important;
}
```

The `font-family: system-ui !important;` overrides any other fonts specified. An additional rule should be added:
```css
input:-internal-autofill-previewed {
   font-family: <customised fonts>;
}
```
